export const MOCK_ROWS = [
  {
    title: 'Fix auth redirect loop',
    repo: 'acme/web',
    status: 'In Review',
    statusColor: 'bg-amber-500/20 text-amber-600 dark:text-amber-400',
    amount: '$250',
  },
  {
    title: 'Add dark mode support',
    repo: 'acme/ui',
    status: 'Merged',
    statusColor: 'bg-emerald-500/20 text-emerald-600 dark:text-emerald-400',
    amount: '$500',
  },
  {
    title: 'Refactor API client',
    repo: 'acme/sdk',
    status: 'In Progress',
    statusColor: 'bg-violet-500/20 text-violet-600 dark:text-violet-400',
    amount: '$750',
  },
  {
    title: 'Update documentation',
    repo: 'acme/docs',
    status: 'Paid',
    statusColor: 'bg-sky-500/20 text-sky-600 dark:text-sky-400',
    amount: '$150',
  },
  {
    title: 'Optimize bundle size',
    repo: 'acme/web',
    status: 'Todo',
    statusColor: 'bg-zinc-500/20 text-zinc-500',
    amount: '$400',
  },
  {
    title: 'Implement webhook handler',
    repo: 'acme/api',
    status: 'In Progress',
    statusColor: 'bg-violet-500/20 text-violet-600 dark:text-violet-400',
    amount: '$600',
  },
  {
    title: 'Fix CORS policy issue',
    repo: 'acme/api',
    status: 'In Review',
    statusColor: 'bg-amber-500/20 text-amber-600 dark:text-amber-400',
    amount: '$200',
  },
  {
    title: 'Add CSV export feature',
    repo: 'acme/web',
    status: 'Merged',
    statusColor: 'bg-emerald-500/20 text-emerald-600 dark:text-emerald-400',
    amount: '$350',
  },
  {
    title: 'Migrate to new auth provider',
    repo: 'acme/sdk',
    status: 'Todo',
    statusColor: 'bg-zinc-500/20 text-zinc-500',
    amount: '$900',
  },
  {
    title: 'Setup CI/CD pipeline',
    repo: 'acme/infra',
    status: 'Paid',
    statusColor: 'bg-sky-500/20 text-sky-600 dark:text-sky-400',
    amount: '$450',
  },
  {
    title: 'Write integration tests',
    repo: 'acme/sdk',
    status: 'In Progress',
    statusColor: 'bg-violet-500/20 text-violet-600 dark:text-violet-400',
    amount: '$300',
  },
  {
    title: 'Redesign settings page',
    repo: 'acme/web',
    status: 'In Review',
    statusColor: 'bg-amber-500/20 text-amber-600 dark:text-amber-400',
    amount: '$550',
  },
];

export const JSON_LD = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'Tasker',
  image: '/home_hero.jpg',
  applicationCategory: 'DeveloperApplication',
  operatingSystem: 'Web',
  description:
    'Tasker is an AI-powered assistant that syncs with GitHub to automatically track bounties, update task statuses, and manage payments across open source repositories.',
  featureList: [
    'AI-powered automatic task status updates',
    'GitHub issue and pull request tracking',
    'Bounty and payment management',
    'Notion-style inline-editable task table',
    '12-status taxonomy for precise task classification',
    'Real-time sync with GitHub activity',
  ],
  offers: {
    '@type': 'Offer',
    price: '0',
    priceCurrency: 'USD',
  },
};
